<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<GenerateAssemblyInfo>true</GenerateAssemblyInfo>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>TrogonEventStore.Plugins</PackageId>
		<Authors>TrogonStack</Authors>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<PackageProjectUrl>https://github.com/TrogonStack/TrogonEventStore.Plugins</PackageProjectUrl>
		<PackageIcon>ouro.png</PackageIcon>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<Description>The interfaces required to create plugins for TrogonEventStore.</Description>
		<PackageReleaseNotes>https://github.com/TrogonStack/TrogonEventStore.Plugins/releases</PackageReleaseNotes>
		<Copyright>Copyright TrogonStack contributors</Copyright>
		<PackageTags>trogoneventstore eventstore plugins</PackageTags>
	</PropertyGroup>

	<PropertyGroup>
		<RepositoryUrl>https://github.com/TrogonStack/TrogonEventStore.Plugins</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.1" />
		<PackageReference Include="YamlDotNet" Version="15.1.4" />
		<PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE.md" Pack="true" PackagePath="\" />
		<None Include="..\..\ouro.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="JetBrains.Annotations" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="EventStore.Plugins.Tests" />
	</ItemGroup>
</Project>
